#!/bin/bash

echo "==== Period Relief Platform Deployment Steps ===="
echo "These changes have been made to fix deployment issues:"
echo "1. Added 'pp-relief-backend.onrender.com' to ALLOWED_HOSTS"
echo "2. Updated CORS settings to allow proper cross-domain communication"
echo "3. Updated CSRF trusted origins to include all necessary domains"
echo "4. Replaced placeholder API functions with real API calls"
echo ""
echo "To deploy these changes:"
echo ""
echo "1. For the backend (Render):"
echo "   - Commit the changes to your repository"
echo "   - Push to the repository connected to Render"
echo "   - Render should automatically deploy the updated code"
echo ""
echo "2. For the frontend (Vercel):"
echo "   - In the Vercel dashboard, add the following environment variable:"
echo "     VITE_API_BASE_URL=https://pp-relief-backend.onrender.com/api"
echo "   - Commit the frontend changes to your repository"
echo "   - Push to the repository connected to Vercel"
echo "   - Vercel should automatically deploy the updated code"
echo ""
echo "3. To verify the changes are working:"
echo "   - Check the browser console for network requests"
echo "   - Verify API calls are going to the correct backend URL"
echo "   - Try logging in and creating product requests"
echo "" 