# Generated by Django 5.2 on 2025-04-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userprofile_is_donor_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Location for individuals or primary location for donors/admins.', max_length=255),
        ),
    ]
